// Singapore postal sectors. The first two digits of an SG postal code map
// deterministically to a postal sector → district. Source: Singapore Post.
// Reference: https://en.wikipedia.org/wiki/Postal_codes_in_Singapore

const PREFIX_MAP: Record<string, string> = {
  '01': 'Raffles Place / Marina',
  '02': 'Raffles Place / Marina',
  '03': 'Raffles Place / Marina',
  '04': 'Cecil / Anson / Tanjong Pagar',
  '05': 'Cecil / Anson / Tanjong Pagar',
  '06': 'High Street / Beach Road',
  '07': 'High Street / Beach Road',
  '08': 'High Street / Beach Road',
  '09': 'Telok Blangah / Harbourfront',
  '10': 'Telok Blangah / Harbourfront',
  '11': 'Pasir Panjang / Hong Leong Garden',
  '12': 'Pasir Panjang / Hong Leong Garden',
  '13': 'Pasir Panjang / Hong Leong Garden',
  '14': 'Queenstown / Tiong Bahru',
  '15': 'Queenstown / Tiong Bahru',
  '16': 'Queenstown / Tiong Bahru',
  '17': 'High Street / Beach Road',
  '18': 'Middle Road / Golden Mile',
  '19': 'Middle Road / Golden Mile',
  '20': 'Little India / Farrer Park',
  '21': 'Little India / Farrer Park',
  '22': 'Orchard / Cairnhill / River Valley',
  '23': 'Orchard / Cairnhill / River Valley',
  '24': 'Ardmore / Bukit Timah / Holland / Tanglin',
  '25': 'Ardmore / Bukit Timah / Holland / Tanglin',
  '26': 'Ardmore / Bukit Timah / Holland / Tanglin',
  '27': 'Ardmore / Bukit Timah / Holland / Tanglin',
  '28': 'Watten Estate / Novena / Thomson',
  '29': 'Watten Estate / Novena / Thomson',
  '30': 'Watten Estate / Novena / Thomson',
  '31': 'Balestier / Toa Payoh / Serangoon',
  '32': 'Balestier / Toa Payoh / Serangoon',
  '33': 'Balestier / Toa Payoh / Serangoon',
  '34': 'Macpherson / Braddell',
  '35': 'Macpherson / Braddell',
  '36': 'Macpherson / Braddell',
  '37': 'Macpherson / Braddell',
  '38': 'Geylang / Eunos',
  '39': 'Geylang / Eunos',
  '40': 'Geylang / Eunos',
  '41': 'Geylang / Eunos',
  '42': 'Katong / Joo Chiat / Amber',
  '43': 'Katong / Joo Chiat / Amber',
  '44': 'Katong / Joo Chiat / Amber',
  '45': 'Katong / Joo Chiat / Amber',
  '46': 'Bedok / Upper East Coast',
  '47': 'Bedok / Upper East Coast',
  '48': 'Bedok / Upper East Coast',
  '49': 'Loyang / Changi',
  '50': 'Loyang / Changi',
  '81': 'Loyang / Changi',
  '51': 'Tampines / Pasir Ris',
  '52': 'Tampines / Pasir Ris',
  '53': 'Hougang / Punggol / Serangoon Garden',
  '54': 'Hougang / Punggol / Serangoon Garden',
  '55': 'Hougang / Punggol / Serangoon Garden',
  '82': 'Hougang / Punggol / Serangoon Garden',
  '56': 'Bishan / Ang Mo Kio',
  '57': 'Bishan / Ang Mo Kio',
  '58': 'Clementi / Upper Bukit Timah',
  '59': 'Clementi / Upper Bukit Timah',
  '60': 'Jurong',
  '61': 'Jurong',
  '62': 'Jurong',
  '63': 'Jurong',
  '64': 'Jurong',
  '65': 'Hillview / Bukit Panjang / Choa Chu Kang',
  '66': 'Hillview / Bukit Panjang / Choa Chu Kang',
  '67': 'Hillview / Bukit Panjang / Choa Chu Kang',
  '68': 'Hillview / Bukit Panjang / Choa Chu Kang',
  '69': 'Lim Chu Kang / Tengah',
  '70': 'Lim Chu Kang / Tengah',
  '71': 'Lim Chu Kang / Tengah',
  '72': 'Kranji / Woodgrove',
  '73': 'Kranji / Woodgrove',
  '75': 'Yishun / Sembawang',
  '76': 'Yishun / Sembawang',
  '77': 'Upper Thomson / Springleaf',
  '78': 'Upper Thomson / Springleaf',
  '79': 'Seletar',
  '80': 'Seletar',
}

// District name from any 6-digit SG postal code. Falls back to a generic
// label if the prefix is unmapped (very rare).
export function districtFromPostal(postalCode: string): string {
  const prefix = postalCode.slice(0, 2)
  return PREFIX_MAP[prefix] ?? 'Singapore'
}
