/**
 * Generate TypeScript coordinate maps from calibration JSON files.
 *
 * Usage (from secretariat/):
 *   node scripts/generate-coords.mjs
 *
 * Reads:  calibration/{form}.json
 * Writes: lib/coords/{form}.ts
 *
 * The generated files are optional — you can import them in lib/pdf.ts once
 * coordinates are finalized instead of maintaining them inline.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root    = join(__dirname, '..')
const calibDir = join(root, 'calibration')
const outDir   = join(root, 'lib', 'coords')

if (!existsSync(calibDir)) {
  console.error('❌  No calibration/ directory found. Run auto-detect.mjs or calibrate.mjs first.')
  process.exit(1)
}

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })

const files = readdirSync(calibDir).filter(f => f.endsWith('.json') && !f.endsWith('.auto.json'))

if (files.length === 0) {
  console.log('No calibration files found (looking for calibration/*.json, not *.auto.json).')
  console.log('Run: node scripts/calibrate.mjs → save → then re-run this script.')
  process.exit(0)
}

for (const file of files) {
  const form = file.replace('.json', '')
  const json = JSON.parse(readFileSync(join(calibDir, file), 'utf-8'))

  // Support both flat format ({ field: {x,y} }) and structured ({ fields: {}, checkboxes: {} })
  const fields    = json.fields    ?? json
  const checkboxes = json.checkboxes ?? {}

  const ts = `// Auto-generated by scripts/generate-coords.mjs
// Source: calibration/${file}
// To regenerate: node scripts/generate-coords.mjs

export const FIELDS = ${JSON.stringify(fields, null, 2)} as const

export const CHECKBOXES = ${JSON.stringify(checkboxes, null, 2)} as const
`

  const outPath = join(outDir, `${form}.ts`)
  writeFileSync(outPath, ts)
  console.log(`✅  Generated: lib/coords/${form}.ts`)
  console.log(`    Fields: ${Object.keys(fields).join(', ')}`)
  if (Object.keys(checkboxes).length > 0) {
    console.log(`    Checkboxes: ${Object.keys(checkboxes).join(', ')}`)
  }
}
